#ifndef PROGRAM_OPTIONS_H
#define PROGRAM_OPTIONS_H

#define WINDOW_TITLE  "Orchard"
#define WINDOW_WIDTH  1280
#define WINDOW_HEIGHT 720

#define PERMANENT_MEMORY_SIZE gigabyte(4)

#endif /* PROGRAM_OPTIONS_H */